version: "3"

services:
  bitcoinzd:
      restart: unless-stopped
      container_name: btcpayserver_bitcoinzd
      image: jagermeister/bitcoinz:latest
      environment:
        BITCOIN_EXTRA_ARGS: |
          rpcport=43782
          ${NBITCOIN_NETWORK:-regtest}=1
          port=39388
          whitelist=0.0.0.0/0
      expose:
        - "43782"
        - "39388"
      volumes:
        - "bitcoinz_datadir:/data"
  nbxplorer:
      environment:
        NBXPLORER_CHAINS: "btcz"
        NBXPLORER_BTCZRPCURL: http://bitcoinzd:43782/
        NBXPLORER_BTCZNODEENDPOINT: bitcoinzd:39388
      volumes:
        - "bitcoinz_datadir:/root/.bitcoinz"
  btcpayserver:
      environment:
        BTCPAY_CHAINS: "btcz"
        BTCPAY_BTCZEXPLORERURL: http://nbxplorer:32838/
volumes:
  bitcoinz_datadir:
